### ISSUE TITLE
Musique CI

### ISSUE THREAD

**Issue by sylvainschmitt** [sylvainschmitt/master-thesis-inp-template#1]
## Musique CI 

![](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/facebook/230/flag-for-cote-divoire_1f1e8-1f1ee.png)

Avant de rentrer je souhaiterais avoir une liste de musique ivoirienne à faire découvrir à mes amis français. À vos claviers:

**Comment by VincyaneBadouard** [comment]
https://youtu.be/iorYbSYmJmQ

**Comment by Ibrahim-Konate** [comment]
```r {List of musician}
Sorry, I'm not fan of music so I don't know the musicians !
```

**Comment by FrejusEDI** [comment]
# 1 Comment faire entrer une figure sur le markdown

**Comment by sylvainschmitt** [comment]
Ceci était un test
