### ISSUE TITLE
Question : Problème rendu logo INPHB page de garde

### ISSUE THREAD

**Issue by FrejusEDI** [sylvainschmitt/master-thesis-inp-template#5]
une fois que je compile le document, la page de garde ne tient plus sur une page avec un excès de l'image du logo de l'INP-HB.

![préoccupation Bookdown](https://user-images.githubusercontent.com/68898813/89170760-a5533000-d56f-11ea-918e-0fe8976de67b.PNG)

**Comment by sylvainschmitt** [comment]
Tu as du modifié le code latex pour générer ton document. Récupère le code d’origine ici : https://github.com/sylvainschmitt/master-thesis-inp-template/blob/master/latex/template.tex

**Comment by sylvainschmitt** [comment]
Notamment tu peux régler ici la taille du logo de l'INPHB qui semble avoir bugé dans ton document:
https://github.com/sylvainschmitt/master-thesis-inp-template/blob/2814c74b20e53bba22b4b0da5e7bddfe3c6cf799/latex/template.tex#L163

**Comment by sylvainschmitt** [comment]
Entre les crochets tu peux préciser la largeur, par exemple `[0.9\linewidth] `

**Comment by FrejusEDI** [comment]
> Tu as du modifié le code latex pour générer ton document. Récupère le code d’origine ici : https://github.com/sylvainschmitt/master-thesis-inp-template/blob/master/latex/template.tex

Je viens de le faire mais le problème est toujours présent

**Comment by sylvainschmitt** [comment]
La solution :
```
 \includegraphics[0.9\linewidth]{images/INPHB.png} \\
```
