### ISSUE TITLE
Titre du chunk coupé par un retour à la ligne

### ISSUE THREAD

**Issue by justinkottou** [sylvainschmitt/master-thesis-inp-template#6]
![20200804_140035](https://user-images.githubusercontent.com/68902569/89303508-d446d000-d65b-11ea-886e-c6f9b9436941.jpg)
Lorsque je lance le rendu pdf on me renvoie toujours un message d'erreur de reconnaissance de package.

**Comment by sylvainschmitt** [comment]
Peux tu envoyer le code des lignes 448 à 449 du fichier `memoire.Rmd` comme précisé par le message d'erreur

**Comment by justinkottou** [comment]
![20200804_140047](https://user-images.githubusercontent.com/68902569/89314515-4671e180-d669-11ea-87a0-56b8e7cd9eaa.jpg)

**Comment by sylvainschmitt** [comment]
Essai de copier les lignes plutôt que de faire des captures d'écran !

**Comment by sylvainschmitt** [comment]
Ligne 447 tu as fait un retour à la ligne dans le titre de ton chunk qu'il faut supprimer.

**Comment by sylvainschmitt** [comment]
Non pas 
```
```{r fig7, bla
bla}
knitr::bla
```
mais
```
```{r fig7, bla bla}
knitr::bla
```

**Comment by sylvainschmitt** [comment]
La prochaine fois demande aux autres, je pense qu'ils auraient pu trouver.

**Comment by justinkottou** [comment]
C'est toujours pareil. Ça ne fonctionne toujours pas
