### ISSUE TITLE
Références Mendeley manquantes dans le fichier bib

### ISSUE THREAD

**Issue by Marieruth97** [sylvainschmitt/master-thesis-inp-template#7]
Bonjour, 
j'arrive pas à trouver les references biblio que je viens d'importer sur Mendeley. ils existent bel et bien dans Mendeley mais pas dans R quand je veux les insérer dans le texte.

**Comment by sylvainschmitt** [comment]
As tu vérifié que les détails de ta référence était bien accepté dans Mendeley ? Tant que tu ne dis pas que c'est bon dans Mendeley, il ne les enregistre pas dans le fichier bib.

**Comment by sylvainschmitt** [comment]
Et as tu mis a jour tes références dans l'add-in citr ?

**Comment by Marieruth97** [comment]
Oui Sylvain j'ai fini par régler le problème. C'était parce que j'avais pas bien exporté les références dans R. Merci
Aussi comment on fait pour diminuer la hauteur et augmenter la largeur d'une figure?

**Comment by sylvainschmitt** [comment]
Tout est expliqué ici : https://bookdown.org/yihui/rmarkdown-cookbook/figure-size.html

Utilise fig.width et fig.height ou out.width et out.height .

**Comment by Marieruth97** [comment]
Merci
