### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by Ibrahim-Konate** [sylvainschmitt/master-thesis-inp-template#8]
je compile mon markdown mais je reçois cette erreur, merci de m'aider

```
pandoc-citeproc.exe: Cannot decode byte '\xad': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error running filter C:/Program Files/RStudio/bin/pandoc/pandoc-citeproc.exe:
Filter returned error status 1
Erreur : pandoc document conversion failed with error 83
Ex�cution arr�t�e

Exited with status 1
```

**Comment by sylvainschmitt** [comment]
Merci de me copier l'ensemble de l'erreur de ta console lors de la compilation (tout le texte à la fin), et de joindre si possible le ficher memoire.Rmd et memoire.tex et memoire.log s'ils existent.

**Comment by Ibrahim-Konate** [comment]
pandoc-citeproc.exe: Cannot decode byte '\xad': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
Error running filter C:/Program Files/RStudio/bin/pandoc/pandoc-citeproc.exe:
Filter returned error status 1
Erreur : pandoc document conversion failed with error 83
Ex�cution arr�t�e

Exited with status 1.
  

c'est tout comme erreur !

**Comment by Ibrahim-Konate** [comment]
[memoire.rmd](https://github.com/sylvainschmitt/master-thesis-inp-template/files/5052260/memoire.rmd)
[memoire.latex](https://github.com/sylvainschmitt/master-thesis-inp-template/files/5052260/memoire.latex)

**Comment by sylvainschmitt** [comment]
Tu as résolu ?

**Comment by Ibrahim-Konate** [comment]
Oui oui j'ai eu la solution Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Sylvain SCHMITT <notifications@github.com> Date : 11/08/2020  08:44  (GMT+00:00) À : sylvainschmitt/master-thesis-inp-template <master-thesis-inp-template@noreply.github.com> Cc : Ibrahim-Konate <amirkonate1@gmail.com>, State change <state_change@noreply.github.com> Objet : Re: [sylvainschmitt/master-thesis-inp-template] Compilation problem (#8) 

Tu as résolu ?
