### ISSUE TITLE
Le chunk de parmètre à été supprimé dans `index.Rmd`

### ISSUE THREAD

**Issue by Marieruth97** [sylvainschmitt/master-thesis-inp-template#9]
Bonjour Sylvain, depuis hier jai un problème de compilation
voila l'erreur affichée  : 

output file: memoire.knit.md

! LaTeX Error: Something's wrong--perhaps a missing \item.

Erreur : LaTeX failed to compile memoire.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See memoire.log for more info.
De plus : Warning messages:
1: package 'cowplot' was built under R version 4.0.2 
2: package 'GGally' was built under R version 4.0.2 
Ex�cution arr�t�e

Exited with status 1

je tenvoie le fichier memoire.rmd et memoire.log

**Comment by Marieruth97** [comment]
jarrive pas à envoyer les fichiers sur github

**Comment by Marieruth97** [comment]
[memoire.log](https://github.com/sylvainschmitt/master-thesis-inp-template/files/5102615/memoire.log)

https://github.com/Marieruth97/memoire-log-rmd/blob/master/memoire.Rmd

Merci de m'aider

**Comment by Marieruth97** [comment]
https://github.com/Marieruth97/memoire-log-rmd/blob/master/memoire.Rmd

**Comment by sylvainschmitt** [comment]
Bonjour,

J'aurais besoin du fichier memoire.tex pour totalement trouver le bug. Mais apparemment c'est une histoire de "highlighting" car tu dois avoir un chunk qu'il essae d'afficher. Si tu regarde la fin du fichier `memoire.log` il te pointe le problème `l.324 \end{Highlighting}`. Tu peux donc vérifier dans ton fichier `memoir.tex` à la ligne 324 quelle chunk est concerné dans ton fichier `memoire.Rmd`. Mais au vu de ton mail, à tout les coups il faut rajouter un `echo=F` dans les options du premier chunk:

```
```{r mmsetup, include=FALSE, echo=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
opts_chunk$set(echo = F, message = F, warning = F, fig.height = 6, fig.width = 6, cache = T)
```

Une autre solution pour ne plus jmais avoir le problème serait de rejouter le package highlighting dans le modèle latex, mais bon j'ai pas trop envie de toucher à votre modèle pour le moment.

Bonne journée,

Sylvain

**Comment by Marieruth97** [comment]
Bien reçu je tenvoie le memoire.tex

**Comment by sylvainschmitt** [comment]
Essaie de suivre et corriger l'erreur avant de m'envoyer le fichier

**Comment by sylvainschmitt** [comment]
Il faut suivre le problème:

1. Commence par vérifier `memoire.log`:

```
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.324 \end{Highlighting}
```

2. Remonte à la ligne correspondant dans `memoire.tex`:

```
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\OperatorTok{::}\KeywordTok{include_graphics}\NormalTok{(}\StringTok{"images/85dcb3e0-f0cd-4d52-8cdf-9ab8c3a7c20d.JPG"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}
```

3. Remonte au chunk correspondant dans `memoire.Rmd`:

```
```{r fig1, fig.cap="Localisation de la forêt classée de Tene", include=TRUE, out.width="0.6\\linewidth", fig.align="center", fig.pos="H"}
knitr::include_graphics("images/85dcb3e0-f0cd-4d52-8cdf-9ab8c3a7c20d.JPG")
```

**Comment by sylvainschmitt** [comment]
Tu as juste désactivé le `echo=FALSE`, rajoute un chunk de paramètres dans ton fichier `index.Rmd` comme précisé ci-dessus:

```
```{r mmsetup, include=FALSE, echo=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
opts_chunk$set(echo = F, message = F, warning = F, fig.height = 6, fig.width = 6, cache = T)
```

**Comment by Marieruth97** [comment]
Après avoir fait ce que tu m'a dit , Il y a une autre erreur

processing file: memoire.Rmd
Error in parse_block(g[-1], g[1], params.src) : duplicate label 'mmsetup'
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
Ex�cution arr�t�e

Exited with status 1.

**Comment by sylvainschmitt** [comment]
**Essaie de suivre et corriger l'erreur avant de me contacter !**

Vous n'êtes pas les seuls en fin de rédaction, ton erreur est écrite noir sur blanc: " duplicate label 'mmsetup'", tu as deux chunks avec le même nom !

**Comment by Marieruth97** [comment]
Merci j'ai pu regler mon problème
